# Generated by Django 4.1.1 on 2022-09-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("i18n", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="name_uz",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
